### ISSUE TITLE
Disabling third party cookies results in player throwing a SecurityError

### ISSUE THREAD

**Issue by JustinBeaudry** [ustream/embedapi#16]
__Repro:__

* disable third party cookies on browser
* navigate to a page with an embedded player
* attempt to play video
* Should see error in console.

__Expected:__

Player should __NOT__ throw an SecurityError and should gracefully degrade and display a message letting the user know that they need to enable Third Party Cookies to use the player.

<img width="735" alt="screen shot 2015-11-16 at 7 47 12 pm" src="https://cloud.githubusercontent.com/assets/686771/11202225/f0022a70-8c9a-11e5-9816-0e94b3ce25ba.png">

**Comment by norbertbieber** [comment]
Hey Justin, good catch, thanks for reporting. We will take care of it.

**Comment by pcdevil** [comment]
Hello Justin,
We have fixed this bug, the player will no longer throw an error when the third-party cookies are disabled!

**Comment by JustinBeaudry** [comment]
@pcdevil This is great news! Thanks!
