### ISSUE TITLE
When calling duration it always returns 0

### ISSUE THREAD

**Issue by mindmelting** [ustream/embedapi#8]
When fetching duration either immediately after creating the Embed object, or even 10 seconds after, it returns 0...

**Comment by necccc** [comment]
On what media type are you fetching duration?
0 is always returned for live content.

**Comment by mindmelting** [comment]
Recorded content, it only returns the duration after the video has properly finished loading in the iframe

**Comment by mindmelting** [comment]
Is there an event that gets fired when I know that the video has finished loading and I can actually fetch the duration?

**Comment by mindmelting** [comment]
Another bug I have noticed, is that when the player has not started yet but it has loaded, it will report a negative duration....

**Comment by necccc** [comment]
Confirmed, there was an issue in mobile browsers with this. We've updated the player, this seems fine for me on iPads for example:

http://necccc.github.io/code/embedapi-getduration.html
