### ISSUE TITLE
Volume/Mute does not work on iOS

### ISSUE THREAD

**Issue by mindmelting** [ustream/embedapi#9]
The 'volume' calMethod option does not do anything on iOS...

**Comment by necccc** [comment]
https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html#//apple_ref/doc/uid/TP40009523-CH5-SW11

> On iOS devices, the audio level is always under the user’s physical control. The volume property is not settable in JavaScript. Reading the volume property always returns 1.

**Comment by mindmelting** [comment]
Would it perhaps make sense to update the documentation to know what you can and can't do on the iOS player?
